version: '3'

services:
  postgres-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres     # define credentials
      POSTGRES_PASSWORD: password # define credentials
      POSTGRES_DB: postgres       # define database
    ports:
      - 5432:5432                 # Postgres port
    networks:
      - postgres-prometheus

  postgres-exporter:
    image: wrouesnel/postgres_exporter:v0.8.0
    restart: always
    environment:
      - DATA_SOURCE_URI=postgres-db:5432/postgres?sslmode=disable
      - DATA_SOURCE_USER=postgres
      - DATA_SOURCE_PASS=password
    ports:
      - "9187:9187"
    networks:
      - postgres-prometheus
    depends_on:
      - postgres-db

  datakit:
    image: guancecloud/datakit:1.6.3-alpha
    ports:
      - "8080:8080"
    networks:
      - postgres-prometheus
    environment:
      - ENV_DATAWAY=https://openway.guance.com?token=${GUANCE_WORKSPACE_TOKEN}
    volumes:
      - ./prom.conf:/usr/local/datakit/conf.d/prom/prom.conf

networks:
  postgres-prometheus:
